/**
 * Logbook tRPC procedures.
 *
 * `logbookProcedure` (in `../trpc.ts`) is the ownership gate: it verifies the
 * Authorization-header bearer token resolves to the `logbookId` in the input
 * and attaches the resolved Logbook to `ctx`. Entry handlers that key off a
 * logbook reuse the same gate.
 *
 * `logbook.listByTokens` is the splash-screen lookup: the client posts every
 * token from localStorage in the body and gets back the corresponding
 * summaries. It does *not* use the Authorization header — the tokens are the
 * input, and authorization is per-token (invalid ones just drop out).
 */
import { z } from "zod";

import type {
  CreatedLogbook,
  LogbookDetail,
  LogbookOverview,
  LogbookSummary,
  EntryNode,
} from "./api-types.ts";
import { Entry } from "../entities/Entry.ts";
import { Logbook } from "../entities/Logbook.ts";
import { logbookProcedure, publicAuthoringProcedure, publicProcedure, router } from "../trpc.ts";
import { issueTokenForLogbook, resolveLogbooksForTokens } from "../tokens.ts";
import { LOGBOOK_NAME_MAX, toLogbookDetail } from "./utils.ts";

// Cap on how many tokens a single splash-screen call will validate. bcrypt is
// intentionally expensive, so a malicious client could otherwise DoS us by
// posting a giant array. A real user with hundreds of logbooks is implausible.
const MAX_LIST_TOKENS = 100;

async function summarize(em: import("@mikro-orm/sqlite").EntityManager, logbooks: Logbook[]) {
  if (logbooks.length === 0) return [];
  const ids = logbooks.map((lb) => lb.id);
  const placeholders = ids.map(() => "?").join(", ");
  const rows = await em
    .getConnection()
    .execute<{ logbook_id: string; count: number | string }[]>(
      `SELECT logbook_id, COUNT(*) AS count FROM entry WHERE logbook_id IN (${placeholders}) GROUP BY logbook_id`,
      ids,
    );
  const counts = new Map<string, number>(rows.map((r) => [r.logbook_id, Number(r.count)]));
  return logbooks.map<LogbookSummary>((lb) => ({
    id: lb.id,
    slug: lb.slug,
    name: lb.name,
    updatedAt: lb.updatedAt,
    entryCount: counts.get(lb.id) ?? 0,
  }));
}

export const logbookRouter = router({
  /**
   * Splash-screen list. Takes an array of tokens (everything in localStorage)
   * and returns summaries for the ones that validate. Tokens that don't
   * resolve are silently dropped so a stale entry doesn't surface as an error
   * — the user simply doesn't see that logbook.
   */
  listByTokens: publicProcedure
    .input(z.object({ tokens: z.array(z.string()).max(MAX_LIST_TOKENS) }))
    .query(async ({ ctx, input }): Promise<LogbookSummary[]> => {
      const logbooks = await resolveLogbooksForTokens(ctx.em, input.tokens);
      logbooks.sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime());
      return summarize(ctx.em, logbooks);
    }),

  overview: logbookProcedure.query(async ({ ctx }): Promise<LogbookOverview> => {
    const lb = ctx.logbook;
    const entries = await ctx.em.find(Entry, { logbook: lb.id }, { orderBy: { order: "asc" } });
    // Bucket children by parent id (entries already arrived in sibling order).
    const byParent = new Map<number | null, Entry[]>();
    for (const e of entries) {
      const pid = e.parent?.id ?? null;
      const list = byParent.get(pid) ?? [];
      list.push(e);
      byParent.set(pid, list);
    }
    const build = (parentId: number | null): EntryNode[] =>
      (byParent.get(parentId) ?? []).map((e) => ({
        id: e.id,
        slug: e.slug,
        name: e.name,
        col: e.col,
        createdAt: e.createdAt,
        updatedAt: e.updatedAt,
        hasContent: e.content != null && e.content.length > 0,
        metadataKeys: e.metadata ? Object.keys(e.metadata) : [],
        children: build(e.id),
      }));
    return { logbook: toLogbookDetail(lb), entries: build(null) };
  }),

  create: publicAuthoringProcedure
    .input(z.object({ name: z.string().max(LOGBOOK_NAME_MAX) }))
    .mutation(async ({ ctx, input }): Promise<CreatedLogbook> => {
      const name = input.name.trim() || "Untitled logbook";
      const lb = ctx.em.create(Logbook, { name });
      ctx.em.persist(lb);
      await ctx.em.flush();
      const token = await issueTokenForLogbook(ctx.em, lb);
      return { logbook: toLogbookDetail(lb), token };
    }),

  rename: logbookProcedure
    .input(z.object({ name: z.string().min(1).max(LOGBOOK_NAME_MAX) }))
    .mutation(async ({ ctx, input }): Promise<LogbookDetail> => {
      const lb = ctx.logbook;
      lb.name = input.name;
      // slug is regenerated by the entity's onUpdate hook
      await ctx.em.flush();
      return toLogbookDetail(lb);
    }),
});
